package admin

import (
	"context"

	"github.com/izzamoe/auto-deploy/internal/deploy"
	"github.com/izzamoe/auto-deploy/internal/store"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ServiceUnitAdminHandler exposes admin API endpoints to preview and apply a
// generated systemd service unit file for an app. Applying writes to a
// system directory as root, so the preview step never touches disk and the
// apply step is only reachable via an explicit follow-up call.
type ServiceUnitAdminHandler struct {
	store *store.AppStore
}

func NewServiceUnitAdminHandler(store *store.AppStore) *ServiceUnitAdminHandler {
	return &ServiceUnitAdminHandler{store: store}
}

// getServiceUnitAppOr404 loads an app by id, writing a 404 JSON response and
// returning false when it does not exist.
func (h *ServiceUnitAdminHandler) getServiceUnitAppOr404(c *app.RequestContext, id string) (*store.App, bool) {
	found, err := h.store.Get(id)
	if err != nil {
		writeAdminAPIErrorHertz(c, consts.StatusNotFound, "App not found")
		return nil, false
	}
	return found, true
}

// PreviewServiceUnitHertz renders the unit file content for the app WITHOUT
// writing anything to disk, so the SPA can show it to the operator before
// they confirm.
func (h *ServiceUnitAdminHandler) PreviewServiceUnitHertz(ctx context.Context, c *app.RequestContext) {
	appRecord, ok := h.getServiceUnitAppOr404(c, c.Param("id"))
	if !ok {
		return
	}

	unit, err := deploy.PreviewServiceUnit(*appRecord)
	if err != nil {
		writeAdminAPIErrorHertz(c, consts.StatusBadRequest, err.Error())
		return
	}

	c.JSON(consts.StatusOK, map[string]any{"unit": unit})
}

// ApplyServiceUnitHertz writes the generated unit file to the systemd unit
// directory (refusing to overwrite any file not previously generated by this
// tool), then runs "systemctl daemon-reload" and "systemctl enable".
func (h *ServiceUnitAdminHandler) ApplyServiceUnitHertz(ctx context.Context, c *app.RequestContext) {
	appRecord, ok := h.getServiceUnitAppOr404(c, c.Param("id"))
	if !ok {
		return
	}

	if err := deploy.ApplyServiceUnit(*appRecord); err != nil {
		if deploy.IsRefuseOverwriteError(err) {
			writeAdminAPIErrorHertz(c, consts.StatusConflict, err.Error())
			return
		}
		writeAdminAPIErrorHertz(c, consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, adminAPIStatusResponse{Status: "ok", Message: "Service unit created and enabled"})
}

func RegisterServiceUnitRoutesHertz(h *server.Hertz, handler *ServiceUnitAdminHandler, auth app.HandlerFunc) {
	api := h.Group("/admin/api", auth)
	api.GET("/apps/:id/service-unit/preview", handler.PreviewServiceUnitHertz)
	api.POST("/apps/:id/service-unit/apply", handler.ApplyServiceUnitHertz)
}
