// Package llmstxt serves the machine-readable project context published at
// /llms.txt and /llms-full.txt, following the llms.txt convention used by
// documentation sites such as developers.cloudflare.com/llms.txt.
//
// The two files are generated by cmd/llmsgen and committed to the repository, so
// that a normal build can embed them without running the generator first.
// Regenerate with `make llms`; `make llms-check` fails when they are stale.
package llmstxt

import (
	"context"
	_ "embed"
	"net/http"
	"runtime"
	"strings"
	"sync"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

//go:embed llms.txt
var rawIndex string

//go:embed llms-full.txt
var rawFull string

// Version is the running build's version, injected at link time with
// -X github.com/izzamoe/auto-deploy/internal/llmstxt.Version=vX.Y.Z. The
// generated files carry a placeholder instead of a literal version so the
// committed artifacts stay stable across releases and the CI drift check only
// reacts to real content changes.
var Version = "dev"

const versionPlaceholder = "{{VERSION}}"

const contentType = "text/plain; charset=utf-8"

// Architecture placeholders resolved at startup. Every application managed by an
// instance is deployed to that same host, so the arch this binary was built for is
// the arch every artifact must target. This is not hardware probing: the server
// process is itself an ELF binary for GOOS/GOARCH that the kernel agreed to run,
// which is exactly the compatibility an agent needs to reproduce.
const (
	goosPlaceholder       = "{{GOOS}}"
	goarchPlaceholder     = "{{GOARCH}}"
	unameArchPlaceholder  = "{{ARCH_UNAME}}"
	rustTargetPlaceholder = "{{RUST_TARGET}}"
)

// archAliases maps GOARCH to the spellings other toolchains use: what `uname -m`
// and `file` report, and the Rust target triple. Only amd64 and arm64 are
// supported hosts; the fallback keeps the output honest rather than inventing a
// triple that would not resolve.
func archAliases(goarch string) (unameArch, rustTarget string) {
	switch goarch {
	case "amd64":
		return "x86_64", "x86_64-unknown-linux-gnu"
	case "arm64":
		return "aarch64", "aarch64-unknown-linux-gnu"
	default:
		return goarch, "(unsupported host architecture — ask the owner)"
	}
}

// Both documents are public on purpose: an llms.txt only serves its function if
// an agent can fetch it without credentials. They describe the API surface, which
// is open source anyway, and never expose per-application data or tokens.
var (
	renderOnce sync.Once
	index      []byte
	full       []byte
)

func render() {
	renderOnce.Do(func() {
		unameArch, rustTarget := archAliases(runtime.GOARCH)
		replacer := strings.NewReplacer(
			versionPlaceholder, Version,
			goosPlaceholder, runtime.GOOS,
			goarchPlaceholder, runtime.GOARCH,
			unameArchPlaceholder, unameArch,
			rustTargetPlaceholder, rustTarget,
		)
		index = []byte(replacer.Replace(rawIndex))
		full = []byte(replacer.Replace(rawFull))
	})
}

// RegisterRoutesHertz mounts the public llms.txt endpoints. No auth middleware is
// applied.
func RegisterRoutesHertz(h *server.Hertz) {
	render()
	h.GET("/llms.txt", serve(func() []byte { return index }))
	h.GET("/llms-full.txt", serve(func() []byte { return full }))
}

func serve(body func() []byte) app.HandlerFunc {
	return func(ctx context.Context, c *app.RequestContext) {
		c.Header("Cache-Control", "public, max-age=3600")
		c.Header("X-Content-Type-Options", "nosniff")
		c.Data(http.StatusOK, contentType, body())
	}
}

// Index returns the rendered llms.txt body. Exported for tests and for callers
// that want the content without going through HTTP.
func Index() []byte {
	render()
	return index
}

// Full returns the rendered llms-full.txt body.
func Full() []byte {
	render()
	return full
}
