package deploy

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/izzamoe/auto-deploy/internal/store"
)

// systemdUnitDir is the directory systemd unit files are written to. It is a
// package-level var (like runSystemctl, renameFile in deploy.go) so tests can
// point it at a t.TempDir() instead of the real /etc/systemd/system.
var systemdUnitDir = "/etc/systemd/system"

// generatedUnitMarker is written as the first line of every unit file this
// tool generates. ApplyServiceUnit refuses to overwrite any existing unit
// file whose first line does not exactly match this marker.
const generatedUnitMarker = "# Generated by auto-deploy -- safe to regenerate; hand edits will be lost on next apply"

// serviceUnitNameRe matches a bare (no ".service" suffix) systemd unit base
// name: letters, digits, underscore, and hyphen only.
var serviceUnitNameRe = regexp.MustCompile(`^[a-zA-Z0-9_-]+$`)

const maxServiceUnitNameLen = 100

// ValidateServiceUnitName validates a bare systemd unit base name (i.e. the
// name WITHOUT any ".service" suffix). It must match ^[a-zA-Z0-9_-]+$ and be
// between 1 and 100 characters. This is a strict, defense-in-depth check:
// the validated name is used to build a filesystem path under
// systemdUnitDir, so anything other than a narrow allow-list of characters
// is rejected outright (no dots, no slashes, no leading dash, no path
// traversal).
func ValidateServiceUnitName(name string) error {
	if name == "" {
		return errors.New("service unit name must not be empty")
	}
	if len(name) > maxServiceUnitNameLen {
		return fmt.Errorf("service unit name too long: %d characters, max %d", len(name), maxServiceUnitNameLen)
	}
	if strings.HasPrefix(name, "-") {
		return fmt.Errorf("service unit name %q must not start with a hyphen", name)
	}
	if !serviceUnitNameRe.MatchString(name) {
		return fmt.Errorf("service unit name %q is invalid: only letters, digits, underscore, and hyphen are allowed", name)
	}
	return nil
}

// serviceUnitBaseAndFile splits an app's ServiceName (which, by existing
// convention in this codebase, is stored including a ".service" suffix, e.g.
// "myapp.service" -- see store.App.ServiceName and its use in
// runSystemctl("restart", app.ServiceName)) into a validated bare base name
// and the exact ".service" filename to write. It validates the base name
// (never the raw ServiceName, which contains a dot) so a malicious or
// malformed ServiceName can never escape systemdUnitDir.
func serviceUnitBaseAndFile(serviceName string) (base string, fileName string, err error) {
	base = strings.TrimSuffix(serviceName, ".service")
	if err := ValidateServiceUnitName(base); err != nil {
		return "", "", err
	}
	return base, base + ".service", nil
}

// cleanSystemdValue strips control characters and leading/trailing whitespace
// from a value that will be interpolated into a systemd unit file. systemd
// parses newlines in a value as directive separators, so any string containing
// \n or \r could inject arbitrary directives.
func cleanSystemdValue(s string) string {
	cleaned := strings.Map(func(r rune) rune {
		if r < 0x20 && r != '\t' {
			return -1
		}
		return r
	}, s)
	return strings.TrimSpace(cleaned)
}

// systemdArgEscaper doubles the two characters systemd expands inside a
// command line: "%" introduces a unit specifier (%h, %n, ...) and "$"
// introduces a variable reference, which silently becomes an empty string when
// the variable is unset. Arguments must reach the binary exactly as the
// operator typed them, so both are escaped to their literal forms ("%%", "$$")
// rather than expanded.
var systemdArgEscaper = strings.NewReplacer("%", "%%", "$", "$$")

// renderExecArgs formats args as the tail of an ExecStart= line: each argument
// is sanitised, escaped, and double-quoted so that whitespace never splits one
// argument into two. strconv.Quote's C-style escaping of "\" and '"' is exactly
// what systemd's own unquoting step reverses.
func renderExecArgs(args []string) string {
	var b strings.Builder
	for _, raw := range args {
		b.WriteString(" ")
		b.WriteString(strconv.Quote(systemdArgEscaper.Replace(cleanSystemdValue(raw))))
	}
	return b.String()
}

// RenderServiceUnit builds the unit file content for app as plain text. It is
// a pure function: no filesystem or network access, which keeps it trivial
// to unit test against an exact expected string.
//
// app.Name, app.BinaryPath and app.Args are sanitised with cleanSystemdValue
// before interpolation to prevent newline injection of arbitrary systemd
// directives.
func RenderServiceUnit(app store.App) string {
	workingDir := filepath.Dir(app.BinaryPath)
	var b strings.Builder
	b.WriteString(generatedUnitMarker)
	b.WriteString("\n")
	fmt.Fprintf(&b, "[Unit]\nDescription=%s (managed by auto-deploy)\nAfter=network.target\n\n", cleanSystemdValue(app.Name))
	fmt.Fprintf(&b, "[Service]\nExecStart=%s%s\nWorkingDirectory=%s\nRestart=on-failure\nRestartSec=5\n", cleanSystemdValue(app.BinaryPath), renderExecArgs(app.Args), workingDir)
	for _, env := range app.EnvVars {
		name := cleanSystemdValue(env.Name)
		if name == "" {
			continue
		}
		// systemd Environment= quotes the value; cleanSystemdValue strips any
		// newline/control chars so the value cannot inject further directives.
		fmt.Fprintf(&b, "Environment=%s=%q\n", name, cleanSystemdValue(env.Value))
	}
	b.WriteString("\n")
	b.WriteString("[Install]\nWantedBy=multi-user.target\n")
	return b.String()
}

// PreviewServiceUnit validates app.ServiceName and returns the rendered unit
// file content WITHOUT writing anything to disk. Callers (e.g. the admin
// preview endpoint) must show this to the operator and require explicit
// confirmation before calling ApplyServiceUnit.
func PreviewServiceUnit(app store.App) (string, error) {
	if _, _, err := serviceUnitBaseAndFile(app.ServiceName); err != nil {
		return "", err
	}
	return RenderServiceUnit(app), nil
}

// errRefuseOverwrite is returned by ApplyServiceUnit when the target unit
// file exists and was not generated by this tool.
var errRefuseOverwrite = errors.New("refusing to overwrite a hand-written unit file -- remove it manually first if you want auto-deploy to manage it")

// IsRefuseOverwriteError reports whether err is the "refusing to overwrite"
// error returned by ApplyServiceUnit, so callers (e.g. the admin HTTP layer)
// can map it to a specific status code (409 Conflict) without string
// matching.
func IsRefuseOverwriteError(err error) bool {
	return errors.Is(err, errRefuseOverwrite)
}

// ApplyServiceUnit validates app.ServiceName (again -- defense in depth,
// never trust a single check), renders the unit file, and writes it to
// systemdUnitDir/<name>.service, refusing to overwrite any existing file
// that was not itself generated by this tool. On a successful write it runs
// "systemctl daemon-reload" then "systemctl enable <name>" (never "start" --
// the caller may not have installed a binary yet).
func ApplyServiceUnit(app store.App) error {
	base, fileName, err := serviceUnitBaseAndFile(app.ServiceName)
	if err != nil {
		return err
	}
	// Defense in depth: validate the base name a second time before any I/O.
	if err := ValidateServiceUnitName(base); err != nil {
		return err
	}

	targetPath := filepath.Join(systemdUnitDir, fileName)

	existing, readErr := os.ReadFile(targetPath)
	switch {
	case readErr == nil:
		firstLine, _, _ := bytes.Cut(existing, []byte("\n"))
		if string(firstLine) != generatedUnitMarker {
			return errRefuseOverwrite
		}
	case errors.Is(readErr, os.ErrNotExist):
		// File absent: nothing to protect, proceed to write.
	default:
		return fmt.Errorf("service_unit: read existing unit file: %w", readErr)
	}

	content := RenderServiceUnit(app)
	if err := os.WriteFile(targetPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("service_unit: write unit file: %w", err)
	}

	if out, err := runSystemctl("daemon-reload"); err != nil {
		return fmt.Errorf("service_unit: daemon-reload: %w: %s", err, string(out))
	}
	if out, err := runSystemctl("enable", base); err != nil {
		return fmt.Errorf("service_unit: enable: %w: %s", err, string(out))
	}
	return nil
}

// SetSystemdUnitDirForTest overrides the systemd unit directory and returns
// a function that restores the previous value. It exists so that other
// packages' tests (e.g. the admin package's HTTP handler tests for the
// preview/apply endpoints) can redirect service unit writes to a t.TempDir()
// without ever touching the real /etc/systemd/system. Package-internal tests
// in this package should instead set the systemdUnitDir var directly.
func SetSystemdUnitDirForTest(dir string) (restore func()) {
	original := systemdUnitDir
	systemdUnitDir = dir
	return func() { systemdUnitDir = original }
}

// SetRunSystemctlForTest overrides the systemctl-invoking function and
// returns a function that restores the previous value. It exists so that
// other packages' tests can capture/stub systemctl invocations without ever
// invoking the real systemctl binary. Package-internal tests in this package
// should instead set the runSystemctl var directly.
func SetRunSystemctlForTest(fn func(name string, args ...string) ([]byte, error)) (restore func()) {
	original := runSystemctl
	runSystemctl = fn
	return func() { runSystemctl = original }
}
